services:
  stellar_web_server:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    command: python manage.py runserver --nostatic 0.0.0.0:8000

  stellar_execute_outgoing_transactions:
    build: .
    env_file: .env
    command: python manage.py execute_outgoing_transactions --loop

  stellar_poll_outgoing_transactions:
    build: .
    env_file: .env
    command: python manage.py poll_outgoing_transactions --loop

  stellar_check_trustlines:
    build: .
    env_file: .env
    command: python manage.py check_trustlines --loop

  stellar_watch_transaction:
    build: .
    env_file: .env
    command: python manage.py watch_transactions
    
  stellar_poll_pending_deposits:
    build: .
    env_file: .env
    command: python manage.py poll_pending_deposits --loop
