services:
  web_server:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    command: python manage.py runserver --nostatic 0.0.0.0:8000

  execute_outgoing_transactions:
    build: .
    env_file: .env
    command: python manage.py execute_outgoing_transactions --loop

  poll_outgoing_transactions:
    build: .
    env_file: .env
    command: python manage.py poll_outgoing_transactions --loop

  check_trustlines:
    build: .
    env_file: .env
    command: python manage.py check_trustlines --loop

  watch_transaction:
    build: .
    env_file: .env
    command: python manage.py watch_transactions
    
  poll_pending_deposits:
    build: .
    env_file: .env
    command: python manage.py poll_pending_deposits --loop
