version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "Dev_grc_anchor"
      POSTGRES_PASSWORD: "Dev_Db_Password"
    ports: 
      - 5432:5432
